kmod/src/alloc.c
kmod/src/alloc.h
kmod/src/data.c

With many concurrent writers we were seeing excessive commits forced
because it thought the data allocator was running low.  The transaction
was checking the raw total_len value in the data_avail alloc_root for
the number of free data blocks.  But this read wasn't locked, and
allocators could completely remove a large free extent and then
re-insert a slightly smaller free extent as they perform their
alloction.  The transaction could see a temporary very small total_len
and trigger a commit.
Data allocations are serialized by a heavy mutex so we don't want to
have the reader try and use that to see a consistent total_len.  Instead
we create a data allocator run-time struct that has a consistent
total_len that is updated after all the extent items are manipulated.
This also gives us a …

Consistently sample data alloc total_len

---

kmod/src/item.c

The item cache page life cycle is tricky.  There are no proper page
reference counts, everthing is done by nesting the page rwlock inside
item_cache_info rwlock.  The intent is that you can only reference pages
while you hold the rwlocks appropriately.  The per-cpu page references
are outside that locking regime so they add a reference count.  Now
there are reference counts for the main cache index reference and for
each per-cpu reference.
The end result of all this is that you can only reference pages outside
of locks if you're protected by references.
Lock invalidation messed this up by trying to add its right split page
to the lru after it was unlocked.  Its page reference wasn't protected
at this point.  Shrinking could be freeing that page, and so it could be
putting a freed page's …

Fix item cache page memory corruption

---

kmod/src/format.h

Remove unused radix_block struct

---

kmod/src/lock.c

The locking protocol only allows one outstanding invalidation request
for a lock at a time.  The client invalidation state is a bit hairy and
involves removing the lock from the invalidation list while it is being
processed which includes sending the response.  This means that another
request can arrive while the lock is not on the invalidation list.  We
have fields in the lock to record another incoming request which puts
the lock back on the list.
But the invalidation work wasn't always queued again in this case.  It
*looks* like the incoming request path would queue the work, but by
definition the lock isn't on the invalidation list during this race.  If
it's the only lock in play then the invalidation list will be empty and
the work won't be queued.  The lock can get stuck with a …

Queue invalidation during previous request

---

kmod/src/dir.c

Our dir methods were trusting dentry args.  The vfs code paths use
i_mutex to protect dentries across revalidate or lookup and method
calls.  But that doesn't protect methods running in other mounts.
Multiple nodes can interleave the initial lookup or revalidate then
actual method call.
Rename got this right.  It is very paranoid about verifying inputs after
acquiring all the locks it needs.
We extend this pattern to the rest of the methods that need to use the
mapping of name to inode (and our hash and pos) in dentries.  Once we
acquire the parent dir lock we verify that the dentry is still current,
returning -EEXIST or -ENOENT as appropriate.
Along these lines, we tighten up dentry info correctness a bit by
updating our dentry info (recording lock coverage and hash/pos) for
negative …

Verify dentries after locking

---

ReleaseNotes.md

Let's try maintaining release notes in a file in the repo.  There are
lots of schemes for associating commits and release notes and this seems
like the simplest place to start.

Add release notes with the 1.0 GA release

---

utils/src/print.c

If a user tries to print a data device exit early if
it is data device.
Signed-off-by: Bryant G. Duffy-Ly <bduffyly@versity.com>

Fix scoutfs print <data_dev> hang

---

kmod/src/server.c

The server's log merge complete request handler was considering the
absence of the client's original request as a failure.  Unfortunately,
this case is possible if a previous server successfully completed the
client's request but the response was lost because it stopped for
whatever reason.
The failure was being logged as a hard error to the console which was
causing tests to occasionally fail during server failover that hit just
as the log merge completion was being processed.
The error was being sent to the client as a response, we just need to
silence the message for these expected but rare errors.
We also fix the related case where the server printed the even more
harsh WARN_ON if there was a next original request but it wasn't the one
we expected to find from our requesting client. …

Silence resent log merge commit error

---

kmod/src/xattr.c

Extended attribute values can be larger than a reasonable maximum size
for our btree items so we store xattrs in many items.  The first pass at
this code used vmalloc to make it relatively easy to work with a
contiguous buffer that was cut up into multiple items.
The problem, of course, is that vmalloc() is expensive.  Well, the
problem is that I always forget just how expensive it can be and use it
when I shouldn't.  We had loads on high cpu count machines that were
catastrophically cpu bound on all the contentious work that vmalloc does
to maintain a coherent global address space.
This removes the use of vmalloc and only allocates a small buffer for
the first compound item.  The later items directly reference regions of
value buffer rather than copying it to and from the large …

Don't use vmalloc in get/set xattr

---

ReleaseNotes.md

Finish the release notes for the 1.3 release.

v1.3 Release

---

ReleaseNotes.md

Finish the release notes for the 1.4 release.

v1.4 Release

---

kmod/src/server.c

Like a lot of places in the server, get_log_trees() doesn't have the
tools in needs to safely unwind partial changes in the face of an error.
In the worst case, it can have moved extents from the mount's log_trees
item into the server's main data allocator.  The dirty data allocator
reference is in the super block so it can be written later.   The dirty
log_trees reference is on stack, though, so it will be thrown away on
error.  This ends up duplicating extents in the persistent structures
because they're written in the new dirty allocator but still remain in
the unwritten source log_trees allocator.
This change makes it harder for that to happen.   It dirties the
log_trees item and always tries to update so that the dirty blocks are
consistent if they're later written out.  If we do get …

Protect get_log_trees corruption with assertion

---

ReleaseNotes.md

Finish the release notes for the 1.5 release.

v1.5 Release

---

ReleaseNotes.md

Finish the release notes for the 1.7 release.

v1.7 Release

---

ReleaseNotes.md

Finish the release notes for the 1.8 release.

v1.8 Release

---

ReleaseNotes.md

Finish the release notes for the 1.9 release.

v1.9 Release

---

ReleaseNotes.md

Finish the release notes for the 1.10 release.

v1.10 Release

---

kmod/src/data.c

The move_blocks ioctl intends to only move extents whose bytes fall inside i_size.  This is easy except for a final extent that straddles an i_size that isn't aligned to 4K data blocks.
The code that either checked for an extent being entirely past i_size or for limiting the number of blocks to move by i_size clumsily compared i_size offsets in bytes with extent counts in 4KB blocks.  In just the right circumstances, probably with the help of a byte length to move that is much larger than i_size, the length calculation could result in trying to move 0 blocks.  Once this hit the loop would keep finding that extent and calculating 0 blocks to move and would be stuck.
We fix this by clamping the count of blocks in extents to move in terms of byte offsets at the start of the loop.  This gets …

Fix move_blocks loop exit conditions

---

ReleaseNotes.md

Finish the release notes for the 1.11 release.

v1.11 Release

---

ReleaseNotes.md

Finish the release notes for the 1.12 release.

v1.12 Release

---

ReleaseNotes.md

Finish the release notes for the 1.13 release.

v1.13 Release

---

ReleaseNotes.md

Finish the release notes for the 1.14 release.

v1.14 Release

---

kmod/src/server.c

Log merge completions were spliced in one server commit.  It's possible to get enough completion work pending that it all can't be completed in one server commit.  Operations fail with ENOSPC and because these changes can't be unwound cleanly the server asserts.
This allows the completion splicing to break the work up into multiple commits.
Processing completions in multiple commits means that request creation can observe the merge status in states that weren't possible before. Splicing is careful to maintain an elevated nr_complete count while the client can't get requests because the tree is rebalancing.

Process log merge splicing in many commits

---

ReleaseNotes.md

Finish the release notes for the 1.15 release.

v1.15 Release

---

ReleaseNotes.md

Finish the release notes for the 1.16 release.

v1.16 Release

---

ReleaseNotes.md

Finish the release notes for the 1.17 release.

v1.17 Release

---

kmod/src/server.c

The server had a few lower level seqcounts that it used to protect state.  One user got it wrong by forgetting to disable pre-emption around writers.  Debug kernels warned as write_seqcount_begin() was called without preemption disabled.
We fix that user and make it easier to get right in the future by having one higher level seqlock and using that consistently for seq read begin/retry and write lock/unlock patterns.

Use seqlock instead of seqcount in server

---

ReleaseNotes.md

Finish the release notes for the 1.18 release.

v1.18 Release

---

tests/funcs/filter.sh

KASAN could raise a spurious warning if the unwinder started in code without ORC metadata and tried to access in the KASAN stack frame redzones.  This was fixed upstream but we can rarely see it in older kernels.  We can ignore these messages.

Ignore spurious KASAN unwind warning

---

ReleaseNotes.md

Finish the release notes for the 1.19 release.

v1.19 Release

---

ReleaseNotes.md

Finish the release notes for the 1.20 release.

v1.20 Release

---

ReleaseNotes.md

Finish the release notes for the 1.21 release.

v1.21 Release

---

tests/tests/createmany-parallel-mounts.sh

This test checks if running multiple jobs at the same time doesn't lock down the machine for too long. This works fine usually because most current hardware we're using for testing takes a few seconds to complete one unit of this test in single threaded mode. But on relatively fast new hardware, the test unit finishes in under 1 second. The timeout threshold calculated therefore becomes (factor * unit-time) = 0, and this makes the test always fail on these fast machines.
To fix, use a 1s bottom time for unit-time, always. We can go to a higher precision if that becomes relevant, or figure out something better later.

Avoid math issues on fast test machines.

---

kmod/src/acl.c
tests/golden/basic-posix-acl
tests/sequence
tests/tests/basic-posix-acl.sh

- test cases for basic acl access patterns (directory, symlink, inheritance of default acls, user/group bits)
- fix ACLs on el8

POSIX ACL fixes for el8, plus tests

---

utils/sparse.sh

We should rely on sparse from epel to do automated sparse checking and not a git tag. But the 0.6.4 build currently fails on sparse/gcc redefines.
This magic Awk from Zach script processes sparse and gcc internal defines and leaves the one intact that sparse doesn't have.
It's wrapped in a simple "atomic" shell test to see if it exists and makes it in a tmp file which renames it into place so that `make -j` properly functions and doesn't cause a midway truncated file.

Sparse fix for epel 0.6.4 sparse - redefines

---

ReleaseNotes.md

Finish the release notes for the 1.22 release.

v1.22 Release

---

kmod/src/Makefile.kernelcompat
kmod/src/ioctl.c
kmod/src/super.c
kmod/src/super.h

3 patches for rhel9.5. Kicking off for CI builds. Still want to make the one patch a little less ugly.

RHEL9.5 kernel support

---

ReleaseNotes.md

Finish the release notes for the 1.23 release.

v1.23 Release

---

ReleaseNotes.md

Finish the release notes for the 1.24 release.

v1.24 Release
