- tests/run-tests.sh
- utils/src/blkid.c
We were checking for the wrong magic value.
We now need to use -f when running mkfs in run-tests for things to work.
> Fix mkfs check for existing ScoutFS superblock

- README.md
- kmod/Makefile
- kmod/src/Makefile
- kmod/src/client.c
- kmod/src/format.h
- kmod/src/server.c
- kmod/src/super.c
- utils/Makefile
- utils/src/mkfs.c
- utils/src/print.c
Instead of hashing headers, define an interop version. Do not mount
superblocks that have a different version, either higher or lower.
Since this is pretty much the same as the format hash except it's a
constant, minimal code changes are needed.
Initial dev version is 0, with the intent that version will be bumped to
1 immediately prior to tagging initial release version.
Update README.
> Filesystem version instead of format hash check

- kmod/src/alloc.c
- kmod/src/counters.h
- kmod/src/data.c
Add a new distinguishable return value (ENOBUFS) from allocator for if
the transaction cannot alloc space. This doesn't mean the filesystem is
full -- opening a new transaction may result in forward progress.
Alter fallocate and get_blocks code to check for this err val and retry
with a new transaction. Handling actual ENOSPC can still happen, of
course.
Add counter called "alloc_trans_retry" and increment it from both spots.
[zab@versity.com: fixed up write_begin error paths]
> Retry if transaction cannot alloc for fallocate or write

- utils/src/stage_release.c
This is checked for by the kernel ioctl code, so giving unaligned values
will return an error, instead of aborting with an assert.
> utils: Do not assert if release is given unaligned offset or length

- tests/sequence
The mount-unmount-race test is occasionally hanging, disable it while we
debug it and have test coverage for unrelated work.
> Disable mount-unmount-race test

- kmod/src/format.h
- kmod/src/net.h
- kmod/src/quorum.c
- utils/src/mkfs.c
- utils/src/parse.c
- utils/src/print.c
Reserve 16 bytes by making scoutfs_inet_addr an array[4] of __le32.
Also add a tag field to differentiate between v4 and v6 usage.
Change code since addr is now an array.
> Reserve space in superblock for IPv6 addresses

- kmod/src/block.c
We're seeing cpu livelocks in block shrinking where counters show that a
single block cache shrink call is only getting EAGAIN from repeated
rhashtable walk attempts.  It occurred to me that the running task might
be preventing an RCU grace period from ending by never blocking.
The hope of this commit is that by waiting for rcu callbacks to run
we'll ensure that any pending rebalance callback runs before we retry
the rhashtable walk again.  I haven't been able to reproduce this easily
so this is a stab in the dark.
> Block cache shrink restart waits for rcu callbacks

- kmod/src/data.c
When move blocks is staging it requires an overlapping offline extent to
cover the entire region to move.
It performs the stage by modifying extents at a time.  If there are
fragmented source extents it will modify each of them at a time in the
region.
When looking for the extent to match the source extent it looked from
the iblock of the start of the whole operation, not the start of the
source extent it's matching.  This meant that it would find a the first
previous online extent it just modified, which wouldn't be online, and
would return -EINVAL.
The fix is to have it search from the logical start of the extent it's
trying to match, not the start of the region.
> Fix accidental EINVAL in move_blocks

- kmod/src/lock.c
The client's incoming lock invalidation request handler triggers a
BUG_ON if it gets a request for a lock that is already processing a
previous invalidation request.  The server is supposed to only send
one request at a time.
The problem is that the batched invalidation request handling will send
responses outside of spinlock coverage before reacquirin the lock and
finishing processing once the response send has been successful.
This gives a window for another invalidation request to arrive after the
response was sent but before the invalidation finished processing.  This
triggers the bug.
The fix is to mark the lock such that we can recognize a valid second
request arriving after we send the response but before we finish
processing.  If it arrives we'll continue invalidation processing …
> Handle back to back invalidation requests

- tests/sequence
- tests/tests/mkdir-rename-rmdir.sh
Add a test which performs mkdir, two renames of the dir, and rmdir on
all possible combinations of mounts.
> Add mkdir-rename-rmdir test

- utils/fenced/scoutfs-fenced.conf.example
- utils/fenced/scoutfs-fenced.service
- utils/scoutfs-utils.spec.in
This should be good enough to get single node mounts up and running with
fenced with minimal effort.  The example config will need to be copied
to /etc/scoutfs/scoutfs-fenced.conf for it to be functional, so this
still requires specific opt-in and wont accidentally run for multi-node
systems.
Signed-off-by: Ben McClelland <ben.mcclelland@versity.com>
> Add fenced systemd and example configs

- kmod/src/xattr.c
- tests/golden/simple-xattr-unit
- tests/tests/simple-xattr-unit.sh
As we update xattrs we need to update any existing old items with the
contents of the new xattr that uses those items.   The loop that updated
existing items only took the old xattr size into account and assumed
that the new xattr would use those items.   If the new xattr size used
fewer parts then the attempt to update all the old parts that weren't
covered by the new size would go very wrong.   The length of the region
in the new xattr would be negative so it'd try to use the max part
length.  Worse, it'd copy these max part length regions outside the
input new xattr buffer.  Typically this would land in addressible memory
and copy garbage into the unused old items before they were later
deleted.
However, it could access so far outside the input buffer that it could
cross a page boudary …
> Fix xattr update out of bounds access

- kmod/src/btree.c
- kmod/src/client.c
- kmod/src/client.h
- kmod/src/net.c
- kmod/src/server.c
- kmod/src/super.c
- tests/funcs/filter.sh
Currently when running certain test cases the code will
hang indefinitely due to forced unmount not clearing up
scoutfs_net_sync_request. The fix here is to call
scoutfs_net_shutdown early for the client and server in order
to clear up the pending message queues.
> Fix client/server abort conn on force unmount

- kmod/src/dir.c
- tests/.gitignore
- tests/Makefile
- tests/golden/renameat2-noreplace
- tests/golden/xfstests
- tests/sequence
- tests/src/dumb_renameat2.c
- tests/tests/renameat2-noreplace.sh
- tests/tests/xfstests.sh
This is just to add the syscall without supporting
any of the flags. This will allow us to pass generic/023
xfstest.
The generic/023 test case only checks renameat2 syscall
without flags.
Signed-off-by: Bryant G. Duffy-Ly <bduffyly@versity.com>
> Add basic renameat2 syscall support

- ReleaseNotes.md
- kmod/src/item.c
The max_seq and active reader mechanisms in the item cache stop readers
from reading old items and inserting them in the cache after newer items
have been reclaimed by memory pressure.  The max_seq field in the pages
must reflect the greatest seq of the items in the page so that reclaim
knows that the page contains items newer than old readers and must not
be removed.
We update the page max_seq as items are inserted or as they're dirtied
in the page.   There's an additional subtle effect that the max_seq can
also protect items which have been erased.  Deletion items are erased
from the pages as a commit completes.   The max_seq in that page will
still protect it from being reclaimed even though no items have that seq
value themselves.
That protection fails if the range of keys containing …
> Preserve item cache page max_seq as items move

- kmod/src/lock_server.c
- kmod/src/net.c
- kmod/src/net.h
- kmod/src/server.c
- tests/golden/client-unmount-recovery
- tests/sequence
- tests/tests/client-unmount-recovery.sh
The set of patches creates a unit test to reproduce the race between client
and server handling lock recovery while farewell is being processed.
It also addresses the issue found from the unit test along with fixing some typos.
> Fix client/server race between lock recov and farewell processing

- kmod/src/counters.h
- kmod/src/lock_server.c
- kmod/src/net.c
- kmod/src/quorum.c
- kmod/src/quorum.h
- kmod/src/server.c
- kmod/src/server.h
Quorum members will try to elect a new leader when they don't receive
heartbeats from the currently elected leader.   This timeout is short to
encourage restoring service promptly.
Heartbeats are sent from the quorum worker thread and are delayed while
it synchronously starts up the server, which includes fencing previous
servers.  If fence requests take too long then heartbeats will be
delayed long enough for remaining quorum members to elect a new leader
while the recently elected server is still busy fencing.
To fix this we decouple server startup from the quorum main thread.
Server starting and stopping becomes asynchronous so the quorum thread
is able to send heartbeats while the server work is off starting up and
fencing.
The server used to call into quorum to clear a flag as it …
> Send quorum heartbeats while fencing

- kmod/src/xattr.c
The change to only allocate a buffer for the first xattr item with
kmalloc instead of the entire logical xattr payload with vmalloc
included a regression for getting large xattrs.
getxattr used to copy the entire payload into the large vmalloc so it
could unlock just after get_next_xattr.   The change to only getting the
first item buffer added a call to copy from the rest of the items but
those copies weren't covered by the locks.  This would often work
because the lock pointer still pointed to a valid lock.  But if the lock
was invalidated then the mode would no longer be compatible and
_item_lookup would return EINVAL.
The fix is to extend xattr_rwsem and cluster lock coverage to the rest
fo the function body, which includes the value item copies.  This also
makes getxattr's lock …
> Fix getxattr with large values giving EINVAL

- kmod/src/server.c
We're seeing allocator motion during get_log_trees dirty quite a lot of
blocks, which makes sense.  Let's continue to up the budget.   If we
still need significantly larger budgets we'll want to look into capping
the dirty block use of the allocator extent movers which will mean
changing callers to support partial progress.
> Increase server commit dirty block budget

- kmod/src/alloc.c
- kmod/src/alloc.h
- kmod/src/server.c
Client log_trees allocator btrees can build up quite a number of
extents.  In the right circumstances fragmented extents can have to
dirty a large number of paths to leaf blocks in the core allocator
btrees.  It might not be possible to dirty all the blocks necessary to
move all the extents in one commit.
This reworks the extent motion so that it can be performed in multiple
commits if the meta allocator for the commit runs out while it is moving
extents.  It's a minimal fix with as little disruption to the ordering
of commits and locking as possible.  It simply bubbles up an error when
the allocators run out and retries functions that can already be retried
in other circumstances.
> Reclaim log_trees alloc roots in multiple commits

- kmod/src/net.c
We were setting sk_allocation on the quorum UDP sockets to prevent
entering reclaim while using sockets but we missed setting it on the
regular messaging TCP sockets.   This could create deadlocks where the
sending socket could enter scoutfs reclaim and wait for server messages
while holding the socket lock, preventing the receive thread from
receiving messages while it blocked on the socket lock.
The fix is to prevent entering the FS to reclaim during socket
allocations.
> Set sk_allocation on TCP sockets

- utils/man/scoutfs.8
- utils/src/print.c
Add an option to skip printing structures that are likely to be so huge
that the print output becomes completely unwieldly on large systems.
> Add skip-likely-huge print option

- kmod/src/alloc.c
Refilling a client's data_avail is the only alloc_move call that doesn't try and limit the number of blocks that it dirties.  If it doesn't find sufficiently large extents it can exhaust the server's alloc budget without hitting the target.  It'll try to dirty blocks and return a hard error.
This changes that behaviour to allow returning 0 if it moved any extents.  Other callers can deal with partial progress as they already limit the blocks they dirty.  This will also return ENOSPC if it hadn't moved anything just as the current code would.
The result is that data fill can not necessarily hit the target.  It might take multiple commits to fill the data_avail btree.
> Allow partial extent motion

- kmod/src/server.c
- kmod/src/srch.c
When a client no longer needs to append to a srch file, for whatever reason, we move the reference from the log_trees item into a specific srch file btree item in the server's srch file tracking btree.
Zeroing the log_trees item and inserting the server's btree item are done in a server commit and should be written atomically.
But commit_log_trees had an error handling case that could leave the newly inserted item dirty in memory without zeroing the srch file reference in the existing log_trees item.  Future attempts to rotate the file reference, perhaps by retrying the commit or by reclaiming the client's rid, would get EEXIST and fail.
This fixes the error handling path to ensure that we'll keep the dirty srch file btree and log_trees item in sync.  The desynced items can still exist in …
> Allow replaying srch file rotation

- kmod/src/super.c
We missed initializing sb->s_time_gran which controls how some parts of the kernel truncate the granularity of nsec in timespec.  Some paths don't use it at all so time would be maintained at full precision.  But other paths, particularly setattr_copy() from userspace and notify_change() from the kernel use it to truncate as times are set.
Setting s_time_gran to 1 maintains full nsec precision.
> Set sb->s_time_gran to support nsecs

- kmod/src/data.c
- tests/golden/data-prealloc
- tests/tests/data-prealloc.sh
Data preallocation attempts to allocate large aligned regions of extents.  It tried to fill the hole around a write offset that didn't contain an extent.  It missed the case where there can be multiple extents between the start of the region and the hole. It could try to overwrite these additional existing extents and writes could return EINVAL.
We fix this by trimming the preallocation to start at the write offset if there are any extents in the region before the write offset.
> Fix partial preallocation when _contig_only = 0

- kmod/scoutfs-kmod.spec.in
- utils/scoutfs-utils.spec.in
The rpmbuild support files no longer define the previously used kernel module macros. This carves out the differences between el7 and el8 with conditionals based on the distro we are building for.
> Add rpm spec file support for el8 builds

- kmod/src/scoutfs_trace.h
- kmod/src/server.c
Server code that wants to dirty blocks by holding a commit won't be allowed to until the current allocators for the server transaction have enough space for the holder.  As an active holder applies the commit the allocators are refilled and the waiting holders will proceed.
But the current allocators can have no resources as the server starts up.  There will never be active holders to apply the commit and refill the allocators.  In this case all the holders will block indefinitely.
The fix is to trigger a server commit when a holder doesn't have room. It used to be that commits were only triggered when apply callers were waiting.  We transfer some of that logic into a new 'committing' field so that we can have commits in flight without apply callers waiting.  We add it to the server …
> Start server commits when holds wait for alloc

- tests/tests/fence-and-reclaim.sh
The fence-and-reclaim test has a little function that runs after fencing and recovery to make sure that all the mounts are operational again. The main thing it does is re-use the same locks across a lot of files to ensure that lock recovery didn't lose any locks that stop forward progress.
But I also threw in a test of the committed_seq machinery, as a bit of belt and suspenders.  The problem is the test is racey.  It samples the seq after the write so the greatest seq it rememebers can be after the write and will not be committed by the other nodes reads.  It being less than the committed_seq is a totally reasonable race.
Which explains why this test has been rarely failing since it was written.  There's no particular reason to test the committed_seq machinery here, so we can just remove …
> Remove seq test from fence-and-reclaim

- tests/funcs/exec.sh
The t_quiet test command execution helper was constantly truncating the
quiet.log with the output of each command.   It was meant to show each
command and its output as they're run.
> t_quiet appends command output

- tests/funcs/filter.sh
On el9 distros systemd-journald will log rotation events into kmesg. Since the default logs on VM images are transient only, they are rotated several times during a single test cycle, causing test failures.
> Filter out journald rotate messages.

- tests/tests/basic-truncate.sh
Without `iflag=fullblock` we encounter sporadic cases where the input file to the truncate test isn't fully written to 8K and ends up to be only 4K. The subsequent truncate tests then fail.
We add a check to the input test file size just to be sure in the future.
> Ensure dd creates the full 8K input test file.

- tests/golden/large-fragmented-free
- tests/tests/large-fragmented-free.sh
Our large fragmented free test creates pathologically file extents which are as expensive as possible to free.  We know that debugging kernels can take a long time to do this so we can extend the hung task timeout.
> Extend hung task timeout for large-fragmented-free

- kmod/src/options.c
The initial code for setting the timeout used the wrong parsed variable.
> Correctly set the log_merge_wait_timeout_ms option

- kmod/scoutfs-kmod.spec.in
This addresses some minor issues with how we handle driving the
weak-modules infrastructure for handling running on kernels not
explicitly built for.
For one, we now drive weak-modules at install-time more explicitly (it
was adding symlinks for all modules into the right place for the running
kernel, whereas now it only handles that for scoutfs against all
installed kernels).
Also we no longer leave stale modules on the filesystem after an
uninstall/upgrade, similar to what's done for vsm's kmods right now.
RPM's pre/postinstall scriptlets are used to drive weak-modules to clean
things up.
Note that this (intentionally) does not regenerate old initrds.
Building this with `set -x` included at the top of both of those scriptlet sections- along with exporting `RPM_SCRIPTLET_DEBUG=1`- yields …
> More cleanly drive weak-modules on install/uninstall

- kmod/src/block.c
- kmod/src/scoutfs_trace.h
Block reads can return ESTALE naturally as mounts read through old cached blocks.  We won't always log it as an error but we should add a tracepoint that can be inspected.
> Add tracepoint as block read returns ESTALE

- utils/src/change_format_version.c
This is overly cautious but should help to avoid most common user errors when passing meta and data device nodes.
We check for dupes, and meta flag set/unset for meta/data device respectively.
> Extra device checks when changing formatversion.

- tests/tests/client-unmount-recovery.sh
The script really wants to print rid instead of pid. But in case of failure, we can just dump the arrays as well.
> Fix the debug output of client-unmount-recovery

- tests/golden/basic-posix-consistency
- tests/golden/change-devices
- tests/golden/quota
- tests/golden/stage-release-race-alloc
- tests/tests/basic-posix-consistency.sh
- tests/tests/change-devices.sh
- tests/tests/quota.sh
- tests/tests/stage-release-race-alloc.sh
The test harness provides a TMP directory for tests to use.  It's badly named.  It's meant to be more of a scratch directory that is not on the FS being tested.
Tests use it both for small log files that give insight into the platform and for large generated files that are not worth saving.  We want to save the directory after test runs to get at the log files, but we don't want to burn a ton of space also saving large generated files
This updates the handful of tests to remove their handful of files that are large enough to be a problem.  With these out of the way we can save the tmp/ directory without its space consumption getting out of hand.
> Clean up large test files

- kmod/src/counters.h
- kmod/src/quota.c
- kmod/src/wkic.c
These new shrinkers were recently added. Because there's very little ways to debug them, or even see them properly function, we should at least add counters for them.
> Add shrinker counters for wkic and quota_info.

- tests/run-tests.sh
This is done by xfstests and it's so much easier to follow what is going on from logs or e.g. serial console that I thought I should do this for scoutfs tests as well. It makes it so much easier to discern which test may have been cause for issues when running a bunch of tests and you're looking back at logs later.
Example output:
```
[ 1505.441333] run scoutfs test basic-block-counts
[ 1506.344674] run scoutfs test basic-bad-mounts
[ 1506.420492] scoutfs f.000000.r.a0a21e error: meta_super META flag not set
[ 1506.427308] scoutfs f.000000.r.72434a error: could not open metadev: error -16
[ 1506.435016] scoutfs f.000000.r.ce1090 error: could not open metadev: error -16
[ 1506.441437] scoutfs f.000000.r.c280d6 error: Unknown or malformed option, "_bad"
[ 1506.543794] run scoutfs test …
```
> Write to kmsg which test we're executing.

- kmod/scoutfs-kmod.spec.in
This is a pretty tiny fix that just deals with a path difference for the weak-modules script (which is only used inside a given minor release series).
> Use path-inspecific weak-modules (EL9 fix)

- kmod/src/ioctl.c
- tests/golden/setattr_more
- tests/tests/setattr_more.sh
A small bug in the translation code from setattr_more to attr_x caused setattr to fail if a size zero was passed but no data version was passed.
Add a small test case for this. Without the fix this will produce the following error output ,and nothing with the fix:
== i_size zero should not require data version to be set
setattr_more ioctl failed on '/mnt/test.0/test/setattr_more/file': Invalid argument (22)
scoutfs: setattr failed: Invalid argument (22)
> Don't pass data version to attr_x unless the ioctl means to set it.

- kmod/scoutfs-kmod.spec.in
We had previously explicitly disabled this; let's start generating them.
> Generate debug packages

- utils/src/bitmap.c
- utils/src/bitmap.h
- utils/src/bloom.c
- utils/src/bloom.h
- utils/src/btree.c
- utils/src/btree.h
- utils/src/list.h
- utils/src/lk_rbtree_wrapper.h
- utils/src/mode_types.c
- utils/src/mode_types.h
- utils/src/name_hash.h
- utils/src/print.c
- utils/src/rbtree.c
- utils/src/rbtree.h
- utils/src/rbtree_augmented.h
- utils/src/rbtree_types.h
- utils/src/srch.c
- utils/src/srch.h
- utils/src/util.h
These were lifted from pr #191.
> Misc. fixes and changes to support parallel_restore and check.

- utils/src/util.c
scoutfs cli commands were using a helper that tried to perform word expansion on the path argument.  This was done with the intent of providing the convenience of shell expansion (env vars, ~) within the cli command argument.
But it breaks paths that accidentally have their file names match the
syntax that wordexp supports.   "[ ]" tripped up files in the wild.
We don't need to provide shell expansion functionality in our argument parsing.  The shell can do that.  The cli must pass the arguments straight through, no parsing at all.
> Remove wordexp expansion of utils path argument

- kmod/src/dir.c
Very old copy/paste bug here, we want to update new_inode's ctime instead. old_inode already is updated.
> Fix new_inode ctime assignment.

- tests/tests/basic-truncate.sh
This happens with the basic-truncate test, only. It's the only user of the `yes` program.
The `yes` command normally fails gracefully under the usual runs that are attached to some terminal. But when the test script runs entirely under something else, it will throw a needless error message that pollutes the test output:
`yes: standard output: Broken pipe`
Adjust the redirect to omit all stderr for `yes` in this case.
> Ignore pipefail alternative error when not a tty.

- tests/funcs/tap.sh
- tests/run-tests.sh
Stored as `results/scoutfs.tap`, this file contains TAP format 14 generated test results.
Embedded in the output are some metadata so that these files can be aggregated and stored in an unique and deduplicating way, but using a generated UUID at the start of testing. The file itself also catches git ID, date, and kernel version, as well as the (possibly altered) test sequence used.
Any test that has diff or dmesg output will be considered failed, and a copy of the relevant data is included as comments.
> TAP formatted output.

- tests/funcs/filter.sh
Example:
```
[ 2469.638414] perf: interrupt took too long (2507 > 2500), lowering kernel.perf_event_max_sample_rate to 79000
```
> Filter out perf `interrupt took too long` dmesg.

- tests/funcs/exec.sh
- tests/tests/lock-recover-invalidate.sh
- tests/tests/orphan-inodes.sh
Occasionally, we have some tests fail because these kills produce:
tests/lock-recover-invalidate.sh: line 42:  9928 Terminated
Even though we expected them to be silent. In these particular cases we already don't care about this output.
We borrow the silent_kill() function from orphan-inodes and promote it to t_silent_kill() in funcs/exec.sh, and then use it everywhere where appropriate.
> Properly silently kill background tasks.

- tests/tests/orphan-inodes.sh
This test regularly fails in CI when the 15 seconds elapses and the system still hasn't concluded the mount log merges and orphan inode scans needed to unlink the test files.
Instead of just extending the timeout value, we test-and-retry for 120s. This hopefully is faster in most cases. My smallest VM needs about 6s-8s on average.
> Extend orphan-inodes timeout.

- tests/run-tests.sh
All these tests don't properly clean up themselves or assume a pristine empty folder when starting, and fall over their own generated test files when repeatedly run without e.g. `-m` (mkfs each time) option passed to the test harnass. And that has implications.
I'm not a fan of tests that fully `rm -rf` everything after a test run because that makes it cumbersome to play around and inspect the test files after a test run. The most minimal change we can make is just to assure that test cases that require some clean initial state is present, will have it. This change does just that.
> Fix test cases that don't run cleanly in a semi-dirty env.

- tests/tests/enospc.sh
The current test sequence performs the unlink and immediately tests whether enough resources are available to create new files again, and this consistently fails.
One of my crummy VMs takes a good 12 seconds before the `touch` actually succeeds. We care about the filesystem eventually returning from ENOSPC, and certainly we don't want it to take forever, but there is a period after our first ENOSPC error and cleanup that we expect ENOSPC to fail for a bit longer.
Make the timeout 120s. As soon as the `touch` completes, exit the wait loop.
> Give enospc test more time to commit unlink.

- kmod/src/server.c
Looks like the compiler isn't smart enough to understand the pass by pointer value, and we can initialize it here easily.
make[1]: Entering directory '/usr/src/kernels/5.14.0-503.26.1.el9_5.x86_64'
CC [M]  /home/auke/scoutfs/kmod/src/server.o
/home/auke/scoutfs/kmod/src/server.c: In function ‘fence_pending_recov_worker’: /home/auke/scoutfs/kmod/src/server.c:4170:23: error: ‘addr.v4.addr’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
4170 |                 ret = scoutfs_fence_start(sb, rid, le32_to_be32(addr.v4.addr),
|                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
4171 |                                           SCOUTFS_FENCE_CLIENT_RECOVERY);
|                                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all …
> Fix -Wmaybe-uninitalized since rhel9.5
